name: shell commands
on: push


jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "test string"

      - name: multiple lines
        run: |
          node -v
          npm -v